settings:
  # Если данная функция выключена, то авто завершение команд при нажатии на таб будет полностью отключено.
  enabled-tab-complete: true
  # Если данная функция включена, то команды с двоеточием будут блокироваться автоматически.
  block-commands-colon: true
  # Если данная функция включена, то команды с двоеточием будут удаляться из авто завершения при нажатии на таб.
  remove-complete-commands-colon: true
  # Сообщение которое будет выводиться при использовании команды с двоеточием. Если поставить '', то сообщения не будет.
  message: '&cНельзя!'
  # Право на использование и авто завершение команд с двоеточием. Если поставить '', то права на обход блокировки не будет.
  permission: 'colon.use'

commands:
  'telegram':
    # Тип блокировки:
    # PLAYER - Блокировка команды для игроков.
    # CONSOLE - Блокировка команды для консоли.
    # ALL - Блокировка команды для игроков и консоли.
    type: 'ALL'
    # Алиасы данной команды. Можно оставить пустыми.
    aliases: []
    # Если данная функция включена, то команда будет автоматически удалена из авто завершения при нажатии на таб.
    remove-complete: true
    # Если данная функция включена, то если эта команда будет иметь несколько аргументов при использовании, то она будет заблокирована.
    block-multiple-args: true
    # Сообщение при использовании даной команды. Если поставить '', то сообщения не будет.
    message: '&cРоскомнадзор заблокировал телеграм.'
    # Право на использование и авто завершение этой команды. Если поставить '', то права на обход блокировки не будет.
    permission: 'telegram.use'
